-- RSWarehouse Installer
-- Run this from Pastebin to install RSWarehouse
-- Usage: pastebin run <pastebin_code>

local GITHUB_REPO = "BRid37/ColonyManager-Pro-RS"
local GITHUB_BRANCH = "main"
local BASE_URL = "https://raw.githubusercontent.com/" .. GITHUB_REPO .. "/" .. GITHUB_BRANCH .. "/"

local FILES_TO_DOWNLOAD = {
    "RSWarehouse.lua",
    "updater.lua",
    "config.lua"
}

local function printColor(text, color)
    if term.isColor() then
        term.setTextColor(color)
    end
    print(text)
    term.setTextColor(colors.white)
end

local function downloadFile(url, filename)
    printColor("Downloading " .. filename .. "...", colors.yellow)
    local response = http.get(url)
    if response then
        local content = response.readAll()
        response.close()
        
        local file = fs.open(filename, "w")
        file.write(content)
        file.close()
        printColor("  Downloaded: " .. filename, colors.green)
        return true
    else
        printColor("  Failed to download: " .. filename, colors.red)
        return false
    end
end

local function createStartup()
    printColor("Creating startup script...", colors.yellow)
    local startup = fs.open("startup.lua", "w")
    startup.write([[
-- RSWarehouse Startup Script
-- Auto-generated by installer

-- Check for updates on boot
print("RSWarehouse - Checking for updates...")
if fs.exists("updater.lua") then
    local success, err = pcall(function()
        dofile("updater.lua")
        if checkForUpdates then
            local updated = checkForUpdates()
            if updated then
                print("Update installed! Rebooting...")
                sleep(2)
                os.reboot()
            end
        end
    end)
    if not success then
        print("Update check failed: " .. tostring(err))
        print("Continuing with current version...")
    end
else
    print("Updater not found, skipping update check")
end

-- Run the main program
print("Starting RSWarehouse...")
sleep(1)
shell.run("RSWarehouse.lua")
]])
    startup.close()
    printColor("  Created: startup.lua", colors.green)
    return true
end

local function createDefaultConfig()
    if fs.exists("config.lua") then
        printColor("Config file already exists, keeping existing settings", colors.yellow)
        return true
    end
    
    printColor("Creating default config...", colors.yellow)
    local config = fs.open("config.lua", "w")
    config.write([[
-- RSWarehouse Configuration
-- Edit this file to customize your setup

return {
    -- GitHub repository for updates
    github_repo = "YOUR_GITHUB_USERNAME/RSWarehouse",
    github_branch = "main",
    
    -- Scan settings
    time_between_runs = 15,
    scan_at_night = true,
    
    -- Logging settings
    verbose_logging = false,
    max_log_size = 50000,
    log_rotate_enabled = true,
    
    -- Storage direction (relative to RS Bridge)
    storage_direction = "back",
    
    -- Excluded items (items that won't be auto-fulfilled)
    -- Add item names or patterns here
    excluded_items = {
        -- Tools are handled specially based on building level
        -- Add any items you want to always exclude here
    },
    
    -- Tool handling settings
    -- When true, provides the cheapest tool that meets requirements
    smart_tool_handling = true,
    
    -- Material tier costs (lower = cheaper, prefer these first)
    material_costs = {
        ["wood"] = 1,
        ["gold"] = 1,
        ["stone"] = 2,
        ["iron"] = 3,
        ["diamond"] = 5,
        ["netherite"] = 10
    },
    
    -- Building level to max tool tier mapping
    -- Building Level 0 = wood/gold max
    -- Building Level 1 = stone max
    -- Building Level 2 = iron max
    -- Building Level 3+ = diamond max
    building_tool_tiers = {
        [0] = {"wood", "gold"},
        [1] = {"wood", "gold", "stone"},
        [2] = {"wood", "gold", "stone", "iron"},
        [3] = {"wood", "gold", "stone", "iron", "diamond"},
        [4] = {"wood", "gold", "stone", "iron", "diamond"},
        [5] = {"wood", "gold", "stone", "iron", "diamond", "netherite"}
    }
}
]])
    config.close()
    printColor("  Created: config.lua", colors.green)
    return true
end

-- Main installer
term.clear()
term.setCursorPos(1, 1)

printColor("========================================", colors.cyan)
printColor("  ColonyManager-Pro-RS Installer", colors.cyan)
printColor("========================================", colors.cyan)
print("")

-- Check for HTTP API
if not http then
    printColor("ERROR: HTTP API is not enabled!", colors.red)
    printColor("Enable it in ComputerCraft config or server settings", colors.yellow)
    return
end

print("This will install ColonyManager-Pro-RS and configure it to")
print("run on startup with automatic updates.")
print("")

printColor("Press any key to continue or Ctrl+T to cancel...", colors.yellow)
os.pullEvent("key")
print("")

-- Download main files
printColor("Downloading files from GitHub...", colors.cyan)
local allSuccess = true

for _, filename in ipairs(FILES_TO_DOWNLOAD) do
    local url = BASE_URL .. filename
    if not downloadFile(url, filename) then
        -- Try to create default if download fails
        if filename == "config.lua" then
            createDefaultConfig()
        else
            allSuccess = false
        end
    end
end

-- Create startup script
createStartup()

-- Create default config if not downloaded
createDefaultConfig()

print("")
if allSuccess then
    printColor("========================================", colors.green)
    printColor("    Installation Complete!", colors.green)
    printColor("========================================", colors.green)
    print("")
    printColor("ColonyManager-Pro-RS will start automatically on boot.", colors.white)
    printColor("It will check for updates from GitHub each time.", colors.white)
    print("")
    printColor("IMPORTANT: GitHub repo already configured for ColonyManager-Pro-RS!", colors.green)
    print("")
    printColor("Rebooting in 5 seconds...", colors.cyan)
    sleep(5)
    os.reboot()
else
    printColor("========================================", colors.orange)
    printColor("  Installation completed with warnings", colors.orange)
    printColor("========================================", colors.orange)
    print("")
    printColor("Some files failed to download.", colors.yellow)
    printColor("Check your GitHub repository URL in config.lua", colors.yellow)
    print("")
    printColor("Press any key to continue...", colors.white)
    os.pullEvent("key")
end
